; b0r4-watch firmware — PlatformIO project for LILYGO T-Watch S3 (SX1262)
[platformio]
default_envs = twatch-s3

[env]
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = fatfs
board_build.partitions = app3M_fat9M_16MB.csv

[env:twatch-s3]
platform = espressif32@6.3.0
framework = arduino
board = LilyGoWatch-S3

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -Wnarrowing
    -DUSER_SETUP_LOADED
    -include include/Setup212_LilyGo_T_Watch_S3.h
    -DUSE_RADIO_SX1262

    -DRADIOLIB_EXCLUDE_NRF24
    -DRADIOLIB_EXCLUDE_RF69
    -DRADIOLIB_EXCLUDE_SX1231
    -DRADIOLIB_EXCLUDE_SI443X
    -DRADIOLIB_EXCLUDE_RFM2X
    -DRADIOLIB_EXCLUDE_SX127X
    -DRADIOLIB_EXCLUDE_AFSK
    -DRADIOLIB_EXCLUDE_AX25
    -DRADIOLIB_EXCLUDE_HELLSCHREIBER
    -DRADIOLIB_EXCLUDE_MORSE
    -DRADIOLIB_EXCLUDE_RTTY
    -DRADIOLIB_EXCLUDE_SSTV
    -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE
    -DRADIOLIB_EXCLUDE_APRS
    -DRADIOLIB_EXCLUDE_BELL

lib_deps =
    https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git#t-watch-s3
    earlephilhower/ESP8266Audio @ 1.9.7
    crankyoldgit/IRremoteESP8266 @ 2.8.6
    jgromes/RadioLib @ 7.1.0
    bodmer/TFT_eSPI @ 2.5.43
    lvgl/lvgl @ 8.4.0
    kosme/arduinoFFT @ 1.6
    lewisxhe/XPowersLib @ 0.2.4
    lewisxhe/SensorLib @ 0.1.8
    mikalhart/TinyGPSPlus @ ^1.0.3
